version: '3'

services:
  web:
    image: php:8.0.16-zts-buster
    container_name: php
    ports:
      # local:container
      - "1337:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      # Volume stockant les fichiers web du projet
      - ./:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile