version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www
    ports:
      - "80:80"
      - "443:443"

  database:
    build:
      context: ./database
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker